plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/workspace/docs"
publishOrigin = "config"
commandOrigin = "config"
base = "/workspace/docs"
command = "echo static"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]