import 'package:flutter/material.dart';
import 'package:calcpro/theme/app_theme.dart';

class CalculatorItem {
  final String title;
  final String shortTitle;
  final String description;
  final String route;
  final IconData icon;
  final Color accent;
  final Color pastel;
  final List<String> tags;

  const CalculatorItem({
    required this.title,
    required this.shortTitle,
    required this.description,
    required this.route,
    required this.icon,
    required this.accent,
    this.pastel = AppColors.pastelLavender,
    this.tags = const ['Popular'],
  });
}

const List<CalculatorItem> kCalculators = [
  CalculatorItem(
    title: 'Percentage Calculator',
    shortTitle: 'Percentage',
    description: 'Calculate percentages with ease',
    route: '/percentage',
    icon: Icons.percent_rounded,
    accent: AppColors.accentPink,
    pastel: AppColors.pastelPink,
    tags: ['Popular', 'Everyday'],
  ),
  CalculatorItem(
    title: 'Mortgage Calculator',
    shortTitle: 'Mortgage',
    description: 'Payment, affordability & schedule',
    route: '/mortgage',
    icon: Icons.home_rounded,
    accent: AppColors.accentBlue,
    pastel: AppColors.pastelBlue,
    tags: ['Popular', 'Finance'],
  ),
  CalculatorItem(
    title: 'Health Calculator',
    shortTitle: 'Health',
    description: 'BMI, ideal weight, BMR & TDEE',
    route: '/health',
    icon: Icons.accessibility_new_rounded,
    accent: AppColors.accentGreen,
    pastel: AppColors.pastelGreen,
    tags: ['Popular', 'Health'],
  ),
  CalculatorItem(
    title: 'EMI / Loan Calculator',
    shortTitle: 'EMI',
    description: 'Monthly EMI + amortization',
    route: '/financial',
    icon: Icons.calculate_rounded,
    accent: AppColors.accentLime,
    pastel: AppColors.pastelLime,
    tags: ['Popular', 'Finance'],
  ),
  CalculatorItem(
    title: 'Tip Calculator',
    shortTitle: 'Tip',
    description: 'Tips & bill splitting',
    route: '/tip',
    icon: Icons.restaurant_rounded,
    accent: AppColors.accentPurple,
    pastel: AppColors.pastelLavender,
    tags: ['Popular', 'Everyday'],
  ),
  CalculatorItem(
    title: 'Discount Calculator',
    shortTitle: 'Discount',
    description: 'Sale prices & savings',
    route: '/discount',
    icon: Icons.local_offer_rounded,
    accent: AppColors.accentPink,
    pastel: AppColors.pastelPink,
    tags: ['Popular', 'Everyday'],
  ),
  CalculatorItem(
    title: 'Sales Tax Calculator',
    shortTitle: 'Sales Tax',
    description: 'Add or remove tax instantly',
    route: '/sales-tax',
    icon: Icons.receipt_long_rounded,
    accent: AppColors.accentOrange,
    pastel: AppColors.pastelOrange,
    tags: ['Popular', 'Finance', 'Business', 'Everyday'],
  ),
  CalculatorItem(
    title: 'Unit Price Calculator',
    shortTitle: 'Unit Price',
    description: 'Compare deals while shopping',
    route: '/unit-price',
    icon: Icons.shopping_bag_outlined,
    accent: AppColors.accentTeal,
    pastel: AppColors.pastelBlue,
    tags: ['Everyday', 'Business'],
  ),
  CalculatorItem(
    title: 'Currency Converter',
    shortTitle: 'Currency',
    description: 'Offline mid-market currency estimates',
    route: '/currency',
    icon: Icons.currency_exchange_rounded,
    accent: AppColors.accentBlue,
    pastel: AppColors.pastelBlue,
    tags: ['Popular', 'Finance', 'Everyday'],
  ),
  CalculatorItem(
    title: 'Compound Interest',
    shortTitle: 'Compound',
    description: 'Compound growth + monthly deposits',
    route: '/savings',
    icon: Icons.savings_outlined,
    accent: AppColors.accentGreen,
    pastel: AppColors.pastelGreen,
    tags: ['Popular', 'Finance'],
  ),
  CalculatorItem(
    title: 'Markup / Margin',
    shortTitle: 'Markup',
    description: 'Retail pricing from cost',
    route: '/markup',
    icon: Icons.storefront_outlined,
    accent: AppColors.accentOrange,
    pastel: AppColors.pastelOrange,
    tags: ['Finance', 'Business'],
  ),
  CalculatorItem(
    title: 'ROI Calculator',
    shortTitle: 'ROI',
    description: 'Investment return percentage',
    route: '/roi',
    icon: Icons.trending_up_rounded,
    accent: AppColors.accentLime,
    pastel: AppColors.pastelLime,
    tags: ['Finance', 'Business'],
  ),
  CalculatorItem(
    title: 'Compare Loans',
    shortTitle: 'Loan Compare',
    description: 'Side-by-side EMI totals',
    route: '/loan-compare',
    icon: Icons.compare_arrows_rounded,
    accent: AppColors.accentPurple,
    pastel: AppColors.pastelLavender,
    tags: ['Finance', 'Business'],
  ),
  CalculatorItem(
    title: 'Refinance Calculator',
    shortTitle: 'Refinance',
    description: 'Savings & break-even months',
    route: '/refinance',
    icon: Icons.sync_alt_rounded,
    accent: AppColors.accentBlue,
    pastel: AppColors.pastelBlue,
    tags: ['Finance'],
  ),
  CalculatorItem(
    title: 'Basic Calculator',
    shortTitle: 'Basic',
    description: 'Everyday arithmetic',
    route: '/basic',
    icon: Icons.dialpad_rounded,
    accent: AppColors.accentPurple,
    pastel: AppColors.pastelLavender,
    tags: ['Everyday'],
  ),
  CalculatorItem(
    title: 'Scientific Calculator',
    shortTitle: 'Scientific',
    description: 'Trig, logs, roots & powers',
    route: '/scientific',
    icon: Icons.science_rounded,
    accent: AppColors.accentPurple,
    pastel: AppColors.pastelLavender,
    tags: ['Everyday'],
  ),
  CalculatorItem(
    title: 'Fraction Calculator',
    shortTitle: 'Fractions',
    description: 'Add, subtract, multiply, divide',
    route: '/fraction',
    icon: Icons.pie_chart_outline_rounded,
    accent: AppColors.accentPink,
    pastel: AppColors.pastelPink,
    tags: ['Everyday'],
  ),
  CalculatorItem(
    title: 'Unit Converter',
    shortTitle: 'Converter',
    description: 'Length, weight, temp, speed & more',
    route: '/convert',
    icon: Icons.swap_vert_rounded,
    accent: AppColors.accentTeal,
    pastel: AppColors.pastelBlue,
    tags: ['Everyday'],
  ),
  CalculatorItem(
    title: 'Fuel Efficiency',
    shortTitle: 'Fuel',
    description: 'MPG, trip cost & cost per mile',
    route: '/fuel',
    icon: Icons.local_gas_station_rounded,
    accent: AppColors.accentOrange,
    pastel: AppColors.pastelOrange,
    tags: ['Everyday'],
  ),
  CalculatorItem(
    title: 'Age Calculator',
    shortTitle: 'Age',
    description: 'Exact age & milestones',
    route: '/age',
    icon: Icons.cake_rounded,
    accent: AppColors.accentOrange,
    pastel: AppColors.pastelOrange,
    tags: ['Health', 'Everyday'],
  ),
  CalculatorItem(
    title: 'Pregnancy Due Date',
    shortTitle: 'Due Date',
    description: 'Estimate from last period',
    route: '/pregnancy',
    icon: Icons.child_friendly_rounded,
    accent: AppColors.accentPink,
    pastel: AppColors.pastelPink,
    tags: ['Health'],
  ),
  CalculatorItem(
    title: 'Time Calculator',
    shortTitle: 'Time',
    description: 'Durations & differences',
    route: '/time',
    icon: Icons.access_time_rounded,
    accent: AppColors.accentGreen,
    pastel: AppColors.pastelGreen,
    tags: ['Everyday'],
  ),
  CalculatorItem(
    title: 'Date Difference',
    shortTitle: 'Date Diff',
    description: 'Days between two dates',
    route: '/date-diff',
    icon: Icons.date_range_rounded,
    accent: AppColors.accentOrange,
    pastel: AppColors.pastelOrange,
    tags: ['Everyday'],
  ),
];

CalculatorItem? calculatorByRoute(String route) {
  for (final c in kCalculators) {
    if (c.route == route) return c;
  }
  return null;
}
